# Generated by Django 3.2.7 on 2021-09-03 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.URLField(max_length=2000)),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'episodes',
            },
        ),
        migrations.CreateModel(
            name='DetailPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=2000)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtoon.episode')),
            ],
            options={
                'db_table': 'detail_pages',
            },
        ),
    ]
